// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAKZhaLLET3Lo9fhOuUbn_1oUVuluqm50',
    appId: '1:522623189789:web:ee26de3e95728f6f5e97f4',
    messagingSenderId: '522623189789',
    projectId: 'my-alharith-first-one',
    authDomain: 'my-alharith-first-one.firebaseapp.com',
    storageBucket: 'my-alharith-first-one.firebasestorage.app',
    measurementId: 'G-6VDNJ859BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHC8Ie-Q6JW1p9cMVVNP9gyiRdW1W4aiQ',
    appId: '1:522623189789:android:c4ab772fcb9b8af25e97f4',
    messagingSenderId: '522623189789',
    projectId: 'my-alharith-first-one',
    storageBucket: 'my-alharith-first-one.firebasestorage.app',
  );
}
